Added more options to AUR script

diff --git a/bin/aur b/bin/aur
--- a/bin/aur
+++ b/bin/aur
@@ -1,6 +1,45 @@
 #!/bin/sh
+
+install=0
+force=0
+quiet=0
+package=
+
+while [[ $# > 0 ]]
+do
+    key=$1
+    case $key in
+        -q|--quiet)
+            quiet=1
+            ;;
+        -f|--force)
+            force=1
+            ;;
+        -i|--install)
+            install=1
+            ;;
+        *)
+            package=$1
+            ;;
+    esac
+    shift
+done
+
 cd ~/src/aur
-p=$1
-url=https://aur.archlinux.org/packages/${p:0:2}/$p/$p.tar.gz
-wget "$url" -O- | tar xz
-cd  $p
+url=https://aur.archlinux.org/packages/${package:0:2}/$package/$package.tar.gz
+
+if [ -d "$package" ]; then
+    if [ $force -ne 1 ]; then
+        if [ $quiet -ne 1 ]; then
+            echo "Looks like $package is already installed."
+            echo 'Use --force to reinstall.'
+        fi
+        exit 1
+    fi
+fi
+
+wget "$url" -qO- | tar xz || { echo "Package $package not found!"; exit 1; }
+if [ $install -eq 1 ]; then
+    cd "$package"
+    makepkg -i
+fi
