Improved checking if programs are installed

diff --git a/bin/gif2webm b/bin/gif2webm
--- a/bin/gif2webm
+++ b/bin/gif2webm
@@ -5,18 +5,12 @@ if [ -z "$1" ]; then
     exit 1
 fi
 
-ffmpeg=$(command -v ffmpeg)
-if [ -z "$ffmpeg" ]; then
-    list=( /cygdrive/z/software/utilities/*ffmpeg*/bin/ffmpeg.exe )
-    ffmpeg="${list[0]}"
-fi
-
-if [ -z "$ffmpeg" ]; then
-    echo ffmpeg not found. 1>&2
+if ! command -v ffmpeg &>/dev/null; then
+    echo 1>&2 'ffmpeg not found. Aborting.'
     exit 1
 fi
 
 in="$1"
 out="$(echo $1|sed 's/gif/webm/i')"
 
-"$ffmpeg" -i "$in" -c:v libvpx -crf 12 -b:v 500K "$out"
+ffmpeg -i "$in" -c:v libvpx -crf 12 -b:v 500K "$out"
diff --git a/bin/napiprojekt b/bin/napiprojekt
--- a/bin/napiprojekt
+++ b/bin/napiprojekt
@@ -2,7 +2,10 @@
 [[ -z "$@" ]] && { echo "No files selected" 1>&2; exit 1; }
 
 for dep in 7z md5sum; do
-    command -v $dep >/dev/null 2>&1 || { echo 1>&2 "$dep is not installed. Aborting."; exit 1; }
+    if ! command -v $dep &>/dev/null; then
+        echo 1>&2 "$dep not found. Aborting."
+        exit 1
+    fi
 done
 
 lang=$(echo "$1"|tr '[:lower:]' '[:upper:]'); shift
diff --git a/bin/radios/lst2pls b/bin/radios/lst2pls
--- a/bin/radios/lst2pls
+++ b/bin/radios/lst2pls
@@ -5,6 +5,11 @@
 lst_file="$1"
 pls_file="$2"
 
+if ! command -v wget &>/dev/null; then
+    echo 1>&2 'wget not found. Aborting.'
+    exit 1
+fi
+
 echo '[playlist]' > "$pls_file"
 
 index=1
