Improved checking if programs are installed

diff --git a/bin/imgop b/bin/imgop
--- a/bin/imgop
+++ b/bin/imgop
@@ -1,4 +1,8 @@
 #!/bin/bash
+if ! command -v convert &>/dev/null; then
+    echo 1>&2 'imagemagick not found. Aborting.'
+    exit 1
+fi
 
 op="$1"
 shift 1
diff --git a/bin/junk/ghost/unpack b/bin/junk/ghost/unpack
--- a/bin/junk/ghost/unpack
+++ b/bin/junk/ghost/unpack
@@ -1,12 +1,12 @@
 #!/bin/sh
 
 if [ "$(id -u)" != '0' ]; then
-    echo 'This script must be run as root' 1>&2
+    echo 1>&2 'This script must be run as root'
     exit 1
 fi
 
 if [ ! -f /backup.tgz ]; then
-    echo 'Backup not found.' 1>&2
+    echo 1>&2 'Backup not found.'
     return 1
 fi
 
diff --git a/bin/thunar-sf b/bin/thunar-sf
--- a/bin/thunar-sf
+++ b/bin/thunar-sf
@@ -12,17 +12,17 @@ file="${file/#\~/$HOME}" #expand tilde to $HOME
 file=${1%/} #remove trailing slash
 
 if [ -z "$file" ]; then
-    echo 'No file selected' 1>&2
+    echo 'No file selected. Aborting.' 1>&2
     exit 1
 fi
 
-if [[ ! $(command -v thunar) ]]; then
-    echo 'Thunar is not installed' 1>&2
+if ! command -v thunar &>/dev/null; then
+    echo 1>&2 'Thunar not found. Aborting.'
     exit 1
 fi
 
-if [[ ! $(command -v xdotool) ]]; then
-    echo 'Xdotool is not installed' 1>&2
+if ! command -v xdotool &>/dev/null; then
+    echo 1>&2 'xdotool not found. Aborting.'
     exit 1
 fi
 
@@ -35,7 +35,7 @@ if [ -d "$file" ]; then
     fi
 else
     if [ ! -f "$file" ]; then
-        echo 'File does not exist' 1>&2
+        echo 'File does not exist. Aborting.' 1>&2
         exit 1
     fi
 
diff --git a/bin/wallpaper b/bin/wallpaper
--- a/bin/wallpaper
+++ b/bin/wallpaper
@@ -1,6 +1,6 @@
 #!/bin/bash
-if [[ ! $(command -v feh) ]]; then
-    echo 'feh is not installed' 1>&2
+if ! command -v feh &>/dev/null; then
+    echo 1>&2 'feh not found. Aborting.'
     exit 1
 fi
 
@@ -24,8 +24,8 @@ elif [ "$1" = set ]; then
     cp "$3" ~/.wallpaper"$2"
 
 elif [ "$1" = identify ]; then
-    if [[ ! $(command -v convert) ]]; then
-        echo 'imagemagick is not installed' 1>&2
+    if ! command -v convert &>/dev/null; then
+        echo 1>&2 'imagemagick not found. Aborting.'
         exit 1
     fi
 
diff --git a/bin/xdiff b/bin/xdiff
--- a/bin/xdiff
+++ b/bin/xdiff
@@ -1,2 +1,7 @@
 #!/bin/sh
+if ! command -v gawk &>/dev/null; then
+    echo 1>&2 'gawk not found. Aborting.'
+    exit 1
+fi
+
 cmp -l "$1" "$2" | gawk '{printf "%08X %02X %02X\n", $1, strtonum(0$2), strtonum(0$3)}'
