mod-git: add git-sq alias

diff --git a/mod-git/gitconfig b/mod-git/gitconfig
--- a/mod-git/gitconfig
+++ b/mod-git/gitconfig
@@ -18,6 +18,33 @@
     df = diff --color --color-words --abbrev
     sw = show --color --color-words --abbrev
     hist = log --pretty=format:\"%Cred%h%Creset %ad %Cblue%<(50,trunc)%s%Creset [%an <%ae>]%d\" --graph --date=short
+    sq = "!f() { \
+            git diff --cached --exit-code &>/dev/null; anything_staged=$?; \
+            git diff --exit-code &>/dev/null; anything_unstaged=$?; \
+            if (( ! $anything_staged )); then \
+                echo "Nothing staged"; \
+                return; \
+            fi; \
+            hash=`git log --pretty=\"format:%h %<(50,trunc)%s%d\"|fzf --no-sort|cut -f1 -d' '`; \
+            message=`git log -n 1 --pretty=format:%s $hash`; \
+            git commit -m \"fixup! $message\"; \
+            if (( $anything_unstaged )); then \
+                git commit -a -m temporary; \
+                staged_hash=`git rev-parse HEAD`; \
+                git reset --hard HEAD^; \
+            fi; \
+            if ! git rebase -i --autosquash; then \
+                echo "Rebase failed, you\\'re on your own. Good luck."; \
+                if (( $anything_unstaged )); then \
+                    echo "Remember to cherry-pick $staged_hash to recover unstaged changes."; \
+                fi; \
+                return; \
+            fi; \
+            if (( $anything_unstaged )); then \
+                git cherry-pick $staged_hash; \
+                git reset HEAD^; \
+            fi; \
+        }; f"
 [diff]
     tool = meld
 [push]
